### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by fanqi** [liferay/lexicon-site#10] opened 2017-04-25 09:31 UTC
```
➜  lexicon-site-master electric run                
Running 'run'...
[17:30:26] Using electric.config.js: /Users/fanqi/Desktop/lexicon-site-master/electric.config.js
[17:30:27] Starting 'build'...
[17:30:27] Starting 'clean'...
[17:30:27] Starting 'clean:dest'...
[17:30:27] Starting 'clean:temp'...
[17:30:27] Finished 'clean:dest' after 6.95 ms
[17:30:27] Finished 'clean:temp' after 4.09 ms
[17:30:27] Finished 'clean' after 9.03 ms
[17:30:27] Starting 'front-matter'...
[17:30:27] Starting 'static'...
[17:30:27] Starting 'styles'...
[17:30:27] Starting 'vendor'...
[17:30:27] Starting 'vendor:codemirror'...
[17:30:27] Starting 'vendor:custom'...
[17:30:27] Finished 'vendor:custom' after 3.41 ms
[17:30:27] Starting 'vendor:senna'...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)

```

**Comment by natecavanaugh** [comment] 2017-05-04 17:46
Hi @fanqi ,
Thanks for reporting this. Could you let me know a bit of information?
Specifically:
1. What version of node are you using?
1. Are you using the latest version of the electric-cli module? (if you're not sure, running `npm install -g electric-cli@alpha` will install it).
1. Are you on the latest version of master for this repo?

If either of the last two questions aren't true, could you update those, and retry and see if you still get the same error?

I can't reproduce it on my end, but I'm not sure if it's an environmental issue.

Thanks!

**Comment by natecavanaugh** [comment] 2017-05-23 20:36
Hi @fanqi ,
Since it's been so long and we can't reproduce this issue on our side, I'm going to go ahead and close this one.
However, if you're able to update the ticket with more info, go ahead and leave a comment and we'll reevaluate if this one should be reopened.

Thanks :)

**Closed by natecavanaugh** 2017-05-23 20:36 UTC
